# Generated by Django 4.2.7 on 2023-11-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_componente', models.CharField(max_length=20)),
                ('descripcion_componente', models.CharField(max_length=100)),
                ('stock_componente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipo', models.CharField(max_length=30)),
                ('descripcion_equipo', models.CharField(max_length=100)),
                ('fecha_antiguedad', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id_estado_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado_equipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado_solicitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTecnico',
            fields=[
                ('id_estado_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado_tecnico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_incidente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=20)),
                ('apell_proveedor', models.CharField(max_length=20)),
                ('cuil_proveedor', models.BigIntegerField()),
                ('tel_proveedor', models.BigIntegerField()),
                ('dom_proveedor', models.CharField(default='sin domicilio', max_length=50)),
                ('correo_proveedor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_solicitud', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tecnico', models.CharField(max_length=20)),
                ('apell_tecnico', models.CharField(max_length=20)),
                ('cuil_tecnico', models.BigIntegerField()),
                ('tel_tecnico', models.BigIntegerField()),
                ('dom_tecnico', models.CharField(default='sin domicilio', max_length=50)),
                ('alias_tecnico', models.CharField(max_length=50)),
                ('contra_tecnico', models.CharField(max_length=50)),
                ('tipo', models.CharField(default='tecnico', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('apell_usuario', models.CharField(max_length=20)),
                ('cuil_usuario', models.BigIntegerField()),
                ('dom_usuario', models.CharField(default='sin domicilio', max_length=50)),
                ('tel_usuario', models.BigIntegerField()),
                ('alias_usuario', models.CharField(max_length=20)),
                ('contra_usuario', models.CharField(max_length=20)),
                ('tipo', models.CharField(default='usuario', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosXSolicitudes',
            fields=[
                ('id_usuarioxsolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_solicitud', models.DateField()),
                ('id_estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.estadosolicitud')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.solicitud')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicosXEstados',
            fields=[
                ('id_tecnicoxestado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_disponible', models.DateField()),
                ('id_estado_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.estadotecnico')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentesXEquipos',
            fields=[
                ('id_incidentexequipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_reparacion', models.CharField(max_length=50)),
                ('fecha_reparacion', models.DateField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.equipo')),
                ('id_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.incidente')),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='id_tecnicoxestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.tecnicosxestados'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='id_usuarioxsolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.usuariosxsolicitudes'),
        ),
        migrations.CreateModel(
            name='EquiposXUsuarios',
            fields=[
                ('id_equipoxusuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_equipo', models.DateField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.equipo')),
                ('id_estado_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.estadoequipo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EquiposXComponentes',
            fields=[
                ('id_equipoxcomponente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_cambio', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateField()),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.componente')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nom_componente_nuevos', models.CharField(max_length=20)),
                ('descripcion_componente_nuevos', models.CharField(max_length=100)),
                ('cantidad_componente_nuevos', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentesXCompras',
            fields=[
                ('id_componentexcompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.componente')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.compra')),
            ],
        ),
    ]
