# Generated by Django 4.2.7 on 2023-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_tecnico_last_login_tecnico_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='password',
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='contra_tecnico',
            field=models.CharField(max_length=50),
        ),
    ]
