# Generated by Django 4.2.7 on 2023-11-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
