# Generated by Django 4.2.7 on 2023-11-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0006_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='ComponentesXCompras',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
