# Generated by Django 4.2.7 on 2023-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0008_user_remove_equiposxcomponentes_id_componente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cuil_tecnico',
            new_name='cuil',
        ),
    ]
