# Generated by Django 4.2.7 on 2023-11-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0009_rename_cuil_tecnico_user_cuil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
