# Generated by Django 4.2.7 on 2023-11-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0012_componente_equipo_estadoequipo_estadosolicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tecnico', models.CharField(max_length=20)),
                ('apell_tecnico', models.CharField(max_length=20)),
                ('cuil_tecnico', models.BigIntegerField()),
                ('tel_tecnico', models.BigIntegerField()),
                ('dom_tecnico', models.CharField(default='sin domicilio', max_length=50)),
                ('alias_tecnico', models.CharField(max_length=50)),
                ('contra_tecnico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('apell_usuario', models.CharField(max_length=20)),
                ('cuil_usuario', models.BigIntegerField()),
                ('dom_usuario', models.CharField(default='sin domicilio', max_length=50)),
                ('tel_usuario', models.BigIntegerField()),
                ('alias_usuario', models.CharField(max_length=20)),
                ('contra_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='equiposxusuarios',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.usuario'),
        ),
        migrations.AlterField(
            model_name='tecnicosxestados',
            name='id_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.tecnico'),
        ),
        migrations.AlterField(
            model_name='usuariosxsolicitudes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.usuario'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
